name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: intall dependencies
      run: 
        sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y || die
        sudo apt-get update || die
        sudo apt-get -y install gcc-arm-embedded || die
    - name: make
      run: 
        cd build
        make all
